services:
  #============================================================================
  # ObjectIO Server - Main S3-compatible API (Development Mode)
  #============================================================================
  objectio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: objectio-server-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Application Configuration
      - RUST_LOG=debug
      - HOST=0.0.0.0
      - PORT=8080
      
      # Database Configuration  
      - DATABASE_URL=surreal://surrealdb:8000/objectio
      - SURREAL_USER=root
      - SURREAL_PASS=objectio_secure_2025
      
      # Redis Configuration
      - REDIS_URL=redis://redis:6379
      
      # Storage Configuration
      - STORAGE_PATH=/app/data
      - MAX_OBJECT_SIZE=5GB
      - ENABLE_VERSIONING=true
      
      # Security Configuration
      - JWT_SECRET=dev-jwt-secret-not-for-production
    volumes:
      - objectio_data:/app/data
      - objectio_logs:/app/logs
      # Mount source code for development
      - ./crates:/app/crates:ro
    depends_on:
      - surrealdb
      - redis
    networks:
      - objectio-network

  #============================================================================
  # SurrealDB - Primary Database
  #============================================================================
  surrealdb:
    image: surrealdb/surrealdb:v2.0.4
    container_name: objectio-surrealdb-dev
    restart: unless-stopped
    command: 
      - start
      - --log=debug
      - --user=root
      - --pass=objectio_secure_2025
      - file:///data/objectio.db
    ports:
      - "8000:8000"
    environment:
      - SURREAL_LOG=debug
    volumes:
      - surrealdb_data:/data
    networks:
      - objectio-network

  #============================================================================
  # Redis - Caching Layer
  #============================================================================
  redis:
    image: redis:7.4-alpine
    container_name: objectio-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass objectio_redis_2025
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=objectio_redis_2025
    volumes:
      - redis_data:/data
    networks:
      - objectio-network

networks:
  objectio-network:
    driver: bridge

volumes:
  objectio_data:
    driver: local
  objectio_logs:
    driver: local
  surrealdb_data:
    driver: local
  redis_data:
    driver: local
